---
- hosts: localhost
  connection: local

  tasks:
    - name: Ensure Docker image is built from the test Dockerfile.
      docker_image:
        name: htb
        path: .
        state: build

    - name: Ensure the test container is running.
      docker_container:
        image: htb:latest
        name: htb
        state: started
